Some fixes and cod improvements
wizardjedi/php-zabbix-agent pull request #1
Opened 2016-11-14 11:18 UTC by ValentinNikolaev

- move Zabbix error to Exception; 
- PSR-1/2 code style; 
- fix ZabbixPrimitiveItem issue; 
- markup changes

2016-11-14 15:10 UTC, wizardjedi requested changes

2016-11-14 15:10 UTC, wizardjedi commented on src/ZabbixAgent.php
> +    protected $items = [];
I think It's better ti use array() instead of [] because of version of php.

2016-11-14 15:10 UTC, wizardjedi commented on src/ZabbixAgent.php
>          if (empty($host)) {
Maybe check port too?

2016-11-14 15:10 UTC, wizardjedi commented on src/ZabbixNotSupportedItem.php
> +    public function create($message)
Must be public static function.

2016-11-14 15:23 UTC, ValentinNikolaev commented on src/ZabbixAgent.php
> +    protected $items = [];
< PHP 5.4 ?

2016-11-14 15:27 UTC, ValentinNikolaev commented on src/ZabbixAgent.php
>          if (empty($host)) {
Nothig changed there. It still checks for port.

2016-11-14 15:44 UTC, wizardjedi commented on src/ZabbixAgent.php
> +    protected $items = [];
Yes :)

2016-11-15 08:45 UTC, wizardjedi commented on src/ZabbixAgent.php
> +    protected $items = [];
Only one issue last for merge ;)

2016-11-15 09:09 UTC, ValentinNikolaev commented on src/ZabbixAgent.php
> +    protected $items = [];
I'll fix in an hour :+1:

2016-11-15 11:12 UTC, wizardjedi approved these changes

2016-11-15 11:14 UTC, merged